# Introduction to Differential Gene Expression Analysis

## Learning Objectives

- Explain and interpret QC on count data using Principal Component Analysis (PCA) and hierarchical clustering
- Implement DESeq2 to obtain a list of significantly different genes
- Perform functional analysis on gene lists with R-based tools

## Installations

[Follow the instructions linked here](../index.html#installation-requirements) to download R and RStudio + Install Packages from CRAN and Bioconductor

## Lessons

### Part 1 (Getting Started)
1. [Workflow (raw data to counts)](./01_RNAseq_processing_workflow.html)
1. [Experimental design considerations](./02_experimental_planning_considerations.html)
1. [Intro to DGE / setting up DGE analysis](./03_DGE_setup_and_overview.html)
     
***

### Part II (QC and setting up for DESeq2)
1. [RNA-seq counts distribution](./04_RNAseq_count_distribution.html)
1. [Count normalization](./05_DGE_count_normalization.html)
1. [Sample-level QC](./06_DGE_QC_analysis.html) (PCA and hierarchical clustering)
1. [Design formulas](./07_design_formulas.html)
1. [Hypothesis testing and multiple test correction](./08_hypothesis_testing.html)

***

### Part III (DESeq2)
1. [Description of steps for DESeq2](./09_DGE_DESeq2_analysis.html)
1. [Wald test results](./10_wald_test_results.html)
1. [Summarizing results and extracting significant gene lists](./11_summarizing_results.html)
1. [Visualization](./12_DGE_visualizing_results.html)
1. [Likelihood Ratio Test results](./13_DGE_LRT_results.html)
1. [Time course analysis](./14_time_course_analyses.html)

***

### Part IV (Functional Analysis)
1. [Gene annotation](./15_genomic_annotation.html)
1. [Functional analysis - over-representation analysis](./16_FA_over-representation_analysis.html)
1. [Functional analysis - functional class scoring / GSEA](./17_FA_functional_class_scoring.html)

***
   
[Workflow Summary](./18_DGE_summarizing_workflow.html)

***

## Building on this workshop
* [Single-cell RNA-seq workshop](https://hbctraining.github.io/scRNA-seq/)
* [RMarkdown](https://hbctraining.github.io/Training-modules/Rmarkdown/)
* [Ggplot2 for functional analysis](https://hbctraining.github.io/Training-modules/Tidyverse_ggplot2/lessons/ggplot2.html)

## Resources
* [DESeq2 vignette](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#theory-behind-deseq2)
* GitHub book on [RNA-seq gene level analysis](http://genomicsclass.github.io/book/pages/rnaseq_gene_level.html)
* [Bioconductor support site](https://support.bioconductor.org/t/deseq2/) (posts tagged with `deseq2`) 
* [Functional analysis visualization](https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html)
